### ISSUE TITLE
是否还会更新李宏毅老师作业的strong baseline

### ISSUE THREAD

**Issue by mengweiwang** [YClemontree/ML2021-HW#1]
你还，请问是否还会更新李宏毅老师作业的strong baseline，刚入门，看了基础代码，进行改写不太会，看到你仓库的strong baseline感觉很好，不知道还会不会更新

**Comment by YClemontree** [comment]
修改到strong baseline会经历比较多的调参等操作，而且Colab不稳定，所以达到strong baseline会占用比较多的时间，大部分可能只是写出能run的代码，效果不好所以不一定会上传。
